// normal
gcc -I src/SDL2/include -L src/SDL2/lib -o main main.c -lmingw32 -lSDL2main -lSDL2
// prevent double windows
gcc -I src/SDL2/include -L src/SDL2/lib -o main main.c -lmingw32 -lSDL2main -lSDL2 -mwindows